In [2]:
import pandas as pd

In [3]:
pip install torch

Requirement already satisfied: torch in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.11.0)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch) (4.13.2)
Requirement already satisfied: setuptools<82 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch) (78.1.0)
Requirement already satisfied: sympy>=1.13.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from torch) (2026.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from jinja2->torch) (3.0.2)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip3.13 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
#these are words to indicate whether something is broken or not working
urgent_keywords = [
    "error", "fail", "crash", "broken", "not working", "exception",
    "bug", "fix", "security", "vulnerability", "memory leak",
    "permission denied", "access denied", "corrupt", "block",
    "issue", "problem"
]

#words that inidcate a question or request for help
help_keywords = [
    "how to", "how do i", "how can i", "difference between",
    "best practice", "performance", "optimize", "upgrade", "migrate",
    "convert", "deprecated", "alternative", "what is", "what does",
    "why is", "why does", "when to use"
]

In [5]:
#map labels to their priority and unknown priority goes to medium
#bug is always high priority, the others will get a keyword check to determine a bump up
labels_map = {
    "BUG": "High",
    "ENH": "Medium",
    "RFC": "Medium",
    "MAINT": "Medium",
    "BLD": "Medium",
    "DEP": "Medium",
    "CI": "Medium",
    "DOC": "Low",
    "TST": "Low",
    "BENCH": "Low",
    "DEV": "Low",
    "TASK": "Low",
    "QUERY": "Low",
    "TYP": "Low",
}
default_priority = "Medium"

In [6]:
#rank mapping so we can bump priority up by one level
priority_rank = {"Low": 0, "Medium": 1, "High": 2}
rank_to_label = {0: "Low", 1: "Medium", 2: "High"}

In [7]:
#loading kaggle train and test data
kaggle_train = pd.read_csv("./archive/university_query_train.csv")
kaggle_test = pd.read_csv("./archive/university_query_test.csv")

print(kaggle_train.shape)
print(kaggle_test.shape)

(5000, 5)
(1000, 5)

In [8]:
#loading github issues
df_github = pd.read_csv("./github_issues_raw.csv")
print(df_github.shape)
print(df_github.head())

(1000, 2)
         source                                           raw_text
0  github_scipy  CI: CodeQL Analyze (cpp) failing about 75% of ...
1  github_scipy  BUG: QMC Sobol' sequences may violate the (0,m...
2  github_scipy           DOC: Intersphinx inventory not available
3  github_scipy  scipy.signal.convolve misses output dimensions...
4  github_scipy  CI: linalg: dev deps failing due to NumPy depr...

In [9]:
#this is to get priority from stackoverflow score
def get_stack_priority(row):
    lowercase = str(row["raw_text"]).lower()
    score = row["Score"]

    # first look: keyword classification
    if any(keyword in lowercase for keyword in urgent_keywords):
        return "High"
    elif any(keyword in lowercase for keyword in help_keywords):
        return "Medium"

    # look 2: high score questions that missed keywords are probably still important
    if score >= 3000:
        return "Medium"
    return "Low"

#loading stackoverflow data and cleaning it to keep the data fields we need
df_stack = pd.read_csv("./QueryResults.csv")
print(df_stack.shape)
print(df_stack.head())

stack_clean = pd.DataFrame({
    "source": df_stack["source"],
    "raw_text": df_stack["raw_text"],
    "priority_label": df_stack.apply(get_stack_priority, axis=1)
})

print(stack_clean.shape)
print(stack_clean["priority_label"].value_counts())
stack_clean.head()

(2000, 3)
          source                                           raw_text  Score
0  stackoverflow  Why is processing a sorted array faster than p...  27519
1  stackoverflow  How do I undo the most recent local commits in...  27203
2  stackoverflow  How do I delete a Git branch locally and remot...  20360
3  stackoverflow  What is the difference between 'git pull' and ...  14045
4  stackoverflow        What does the "yield" keyword do in Python?  13130
(2000, 3)
priority_label
Medium    1164
Low        748
High        88
Name: count, dtype: int64

,source,raw_text,priority_label
0,stackoverflow,Why is processing a sorted array faster than p...,Medium
1,stackoverflow,How do I undo the most recent local commits in...,Medium
2,stackoverflow,How do I delete a Git branch locally and remot...,Medium
3,stackoverflow,What is the difference between 'git pull' and ...,Medium
4,stackoverflow,"What does the ""yield"" keyword do in Python?",Medium

In [10]:
# cleaning kaggle data to keep the data fields we need 
kaggle_train_clean = pd.DataFrame({
    "source": "kaggle",
    "raw_text": kaggle_train["Student_Query"],
    "priority_label": kaggle_train["Priority_Label"]
})

kaggle_test_clean = pd.DataFrame({
    "source": "kaggle",
    "raw_text": kaggle_test["Student_Query"],
    "priority_label": kaggle_test["Priority_Label"]
})

print(kaggle_train_clean.shape)
kaggle_train_clean.head()

(5000, 3)

   source                                           raw_text priority_label
0  kaggle                         How to join student clubs?            Low
1  kaggle               My admit card has incorrect details.           High
2  kaggle        How to reset my university portal password?         Medium
3  kaggle  My exam form is not submitted and tomorrow is ...           High
4  kaggle  I cannot download my hall ticket for tomorrow'...           High

In [11]:
# function to get priority from the title prefix and check keywords
def get_priority(title):
    label = title.split(":")[0].strip()
    starting_priority = labels_map.get(label, default_priority)
    body = title.lower()
    #bug is always high, skip the keyword check
    if label == "BUG":
        return "High"
    #for ambiguous labels check if the description has urgency keywords
    if any(keyword in body for keyword in urgent_keywords):
        bump_up = min(priority_rank[starting_priority] + 1, 2)
        return rank_to_label[bump_up]
    return starting_priority


# cleaning github data to keep the three schema columns
github_clean = pd.DataFrame({
    "source": df_github["source"],
    "raw_text": df_github["raw_text"],
    "priority_label": df_github["raw_text"].apply(get_priority)
})

print(github_clean.shape)
github_clean.head()

(1000, 3)

,source,raw_text,priority_label
0,github_scipy,CI: CodeQL Analyze (cpp) failing about 75% of ...,High
1,github_scipy,"BUG: QMC Sobol' sequences may violate the (0,m...",High
2,github_scipy,DOC: Intersphinx inventory not available,Low
3,github_scipy,scipy.signal.convolve misses output dimensions...,Medium
4,github_scipy,CI: linalg: dev deps failing due to NumPy depr...,High

In [16]:
from sklearn.model_selection import train_test_split
stack_train, stack_test = train_test_split(stack_clean, test_size = 0.2)
stack_train.to_csv("./dataset/stack_train.csv", index=False)
stack_test.to_csv("./dataset/stack_test.csv", index=False)

In [15]:
kaggle_train_clean.to_csv("./dataset/kaggle_train_clean.csv", index=False)
kaggle_test_clean.to_csv("./dataset/kaggle_test_clean.csv", index=False)


github_clean.to_csv("./dataset/github_clean.csv", index = False)